### PR TITLE
DSG OT variant

### LINKED ISSUE #56: [BUG]:
## Description

The system crashes when trying to run with more than 58 participants. The error message indicates that the factorial of 58 is too large to fit in 256 bits.

Error message:
```
thread 'main' panicked at crates/sl-mpc-mate/src/math.rs:191:9:
Factorial of 58 is too large to fit in 256 bits
```

### Reproduce

1. Initialize a DKG process with n=100 participants and threshold t=59
2. Run the following code:

```rust
println!("\n[BENCHMARK] Starting DKG process");
let n = 100;
let t = 59;

// Round 0: initialization
let init_start = Instant::now();
println!("[BENCHMARK] Initializing {} parties with threshold {}", n, t);

let mut parties: Vec<State> = (0..n)
    .map(|party_id| State::new(
        Party { ranks: vec![0u8; n], party_id: party_id as u8, t: t as u8 },
        &mut thread_rng(),
    ))
    .collect();
```

## Expected Behavior

The system should be able to handle more than 58 participants without crashing.

## Environment

Please complete the following information:

OS + Version: macOS Sequoia 15.3.1

Cargo Version: rustc 1.85.0 (4d91de4e4 2025-02-17)

HW type: Mac

## Additional context

The error occurs in the math.rs file at line 191, suggesting that there might be a limitation in the data type used for factorial calculations. The system needs to be able to handle factorials of numbers greater than 58 within 256-bit constraints or implement a different approach for large participant groups.

### PR DESCRIPTION
**Pull request by eclipse7**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🔁 CI/CD
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR:
- updates sl-compute version
- adds DSG with basic OT instead of OT extension

## Related Tickets
- [Fixes # (issue)](https://github.com/silence-laboratories/dkls23-rs/issues/250)
- Fixes #56 

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

File: src/dsg_ot_variant.rs [hunk 1]
```diff
@@ -0,0 +1,660 @@
...
+use zeroize::{Zeroize, ZeroizeOnDrop};
+
+use sl_mpc_mate::bip32::BIP32Error;
+
+use crate::dsg::{
+    combine_partial_signature, derive_with_offset, get_lagrange_coeff,
+    get_zeta_i, PartialSignature, PreSignature, SignMsg1, SignMsg4, PS,
+};
+pub use crate::error::SignError;
+use crate::error::SignOTVariantError;
```
Comment (bitgo-keenan) [inline src/dsg_ot_variant.rs:27]: This should probably be `pub`

File: src/dsg_ot_variant.rs [hunk 2]
```diff
@@ -0,0 +1,660 @@
...
+            commitment_r_i: *self.commitment_r_i_list.find_pair(party_id),
+        }
+    }
+
+    /// Round 1
+    pub fn handle_msg1<R: RngCore + CryptoRng>(
+        &mut self,
+        rng: &mut R,
+        msgs: Vec<SignMsg1>,
+    ) -> Result<Vec<SignMsg2>, SignOTVariantError> {
```
Comment (bitgo-keenan) [inline src/dsg_ot_variant.rs:169]: `SignOTVariantError` is private, but it is in a public interface, so it should be `pub`. The compiler didn't catch this probably because `SignOTVariantError` derives `thiserror::Error` which is public.

File: src/dsg_ot_variant.rs (hunk 1 above)
Comment (eclipse7) [reply src/dsg_ot_variant.rs]: Added

**Review by bitgo-keenan — APPROVED** [review]

**Review by left-arm — APPROVED** [review]
